### ISSUE TITLE
Replace URIParser with URIs

### ISSUE THREAD

**Issue by jmkuhn** [rofinn/FilePaths.jl#56]
The README for [URIParser](https://github.com/JuliaWeb/URIParser.jl) indicates that it is deprecated in favor of [URIs](https://github.com/JuliaWeb/URIs.jl). Should we change the dependency for this package?  This would be a breaking change so if we are going to make the change it should be before tagging 1.0.  I could submit a PR if you agree that this should be done.

**Comment by rofinn** [comment]
Yes, a PR would be appreciated :) Scanning the docs it looks pretty similar, so updating the code here shouldn't be too difficult. Since we support 3rd party packages like that with Requires.jl we could probably support both package for a deprecation cycle and throw a `depwarn` when loading the URIParser glue code.
